[programs.localnet]
anchor_escrow = "2gSyVrvohTuae4WQZcrVUdV5vhfxWmbGkPjYJjiZx6rX"

[registry]
url ="http://127.0.0.1:8899"

[provider]
cluster = "https://holy-autumn-daylight.solana-devnet.quiknode.pro/f79aa971b5e5d9b72f0e1b55109dabed8d0b98a8/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
